### ISSUE TITLE
Linux Install

### ISSUE THREAD

**Issue by MaDTaZ** [tingtom/Readarr#4]
Hey 
More of a question then a request do you have instructions on how to run in liunx mint?

MaDTaZ

**Comment by tingtom** [comment]
Hi,

I've only been running it on Windows for development, I would suggest looking at how Sonarr is ran on Linux as it should be very similar.

**Comment by MaDTaZ** [comment]
So the only question I have is I cannot find where the .exe is.  I run sonarr under mono.  So I should be able to do the samething.

**Comment by tingtom** [comment]
You'd have to build it from source, I haven't made a release since it's still in development.

**Comment by MaDTaZ** [comment]
No problem I will try to figure that out

**Comment by MaDTaZ** [comment]
Thanks Tingtom. Appreciate the work look super interesting and looking forward in helping out anyway I can

**Comment by tingtom** [comment]
np, currently merging the newest Sonarr V3 changes to a new branch
