### ISSUE TITLE
Rebase to include Sonarr commits since fork

### ISSUE THREAD

**Issue by tbg7992** [tingtom/Readarr#7]
It has been a while since this was forked from Sonarr, and the repository is many commits behind. I am looking into rebasing on top of Sonarr to pull any bug fixes etc. It doesn't look like too many changes have occurred since the fork, so it should be relatively straightforward and useful.

What do you think?

**Comment by tingtom** [comment]
Have created a new branch for Sonarr V3, cherrypicked my Github changes and binned off my old code
